// This is used because it brings significant savings over the transit-js published to npm.
// It is brought in via webpack alias

// transit-js 0.8.861
// http://transit-format.org
//
// Copyright 2014 Cognitect. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License..
;(function(){var c=this;
  function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
  b&&"undefined"==typeof a.call)return"object";return b};function k(a,b,d){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=d(b)};function l(a,b){this.H=a|0;this.B=b|0}var ba={},ca={};function m(a){return k(ba,a,function(a){return new l(a,0>a?-1:0)})}function da(a){a|=0;return-128<=a&&128>a?m(a):new l(a,0>a?-1:0)}function p(a){return isNaN(a)?m(0):a<=-ea?q():a+1>=ea?fa():0>a?r(p(-a)):new l(a%t|0,a/t|0)}function u(a,b){return new l(a,b)}
  function v(a,b){if(!a.length)throw Error("number format error: empty string");var d=b||10;if(2>d||36<d)throw Error("radix out of range: "+d);if("-"==a.charAt(0))return r(v(a.substring(1),d));if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);for(var e=p(Math.pow(d,8)),f=m(0),g=0;g<a.length;g+=8){var h=Math.min(8,a.length-g),n=parseInt(a.substring(g,g+h),d);8>h?(h=p(Math.pow(d,h)),f=w(f,h).add(p(n))):(f=w(f,e),f=f.add(p(n)))}return f}var t=4294967296,ea=t*t/2;
  function fa(){return k(ca,ga,function(){return u(-1,2147483647)})}function q(){return k(ca,ha,function(){return u(0,-2147483648)})}function ia(){return k(ca,ja,function(){return da(16777216)})}function x(a){return a.B*t+(0<=a.H?a.H:t+a.H)}
  l.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(y(this))return"0";if(0>this.B){if(this.equals(q())){var b=p(a);var d=z(this,b);b=A(w(d,b),this);return d.toString(a)+b.H.toString(a)}return"-"+r(this).toString(a)}d=p(Math.pow(a,6));b=this;for(var e="";;){var f=z(b,d),g=(A(b,w(f,d)).H>>>0).toString(a);b=f;if(y(b))return g+e;for(;6>g.length;)g="0"+g;e=""+g+e}};function y(a){return!a.B&&!a.H}l.prototype.equals=function(a){return this.B==a.B&&this.H==a.H};
  function C(a,b){if(a.equals(b))return 0;var d=0>a.B,e=0>b.B;return d&&!e?-1:!d&&e?1:0>A(a,b).B?-1:1}function r(a){return a.equals(q())?q():u(~a.H,~a.B).add(m(1))}l.prototype.add=function(a){var b=this.B>>>16,d=this.B&65535,e=this.H>>>16,f=a.B>>>16,g=a.B&65535,h=a.H>>>16;a=0+((this.H&65535)+(a.H&65535));h=0+(a>>>16)+(e+h);e=0+(h>>>16);e+=d+g;b=0+(e>>>16)+(b+f)&65535;return u((h&65535)<<16|a&65535,b<<16|e&65535)};function A(a,b){return a.add(r(b))}
  function w(a,b){if(y(a)||y(b))return m(0);if(a.equals(q()))return 1==(b.H&1)?q():m(0);if(b.equals(q()))return 1==(a.H&1)?q():m(0);if(0>a.B)return 0>b.B?w(r(a),r(b)):r(w(r(a),b));if(0>b.B)return r(w(a,r(b)));if(0>C(a,ia())&&0>C(b,ia()))return p(x(a)*x(b));var d=a.B>>>16,e=a.B&65535,f=a.H>>>16,g=a.H&65535,h=b.B>>>16,n=b.B&65535,ra=b.H>>>16,U=b.H&65535;var ya=0+g*U;var O=0+(ya>>>16)+f*U;var B=0+(O>>>16);O=(O&65535)+g*ra;B+=O>>>16;B+=e*U;var V=0+(B>>>16);B=(B&65535)+f*ra;V+=B>>>16;B=(B&65535)+g*n;V=V+
  (B>>>16)+(d*U+e*ra+f*n+g*h)&65535;return u((O&65535)<<16|ya&65535,V<<16|B&65535)}
  function z(a,b){if(y(b))throw Error("division by zero");if(y(a))return m(0);if(a.equals(q())){if(b.equals(m(1))||b.equals(m(-1)))return q();if(b.equals(q()))return m(1);var d=1;var e=a.B;d=32>d?u(a.H>>>d|e<<32-d,e>>d):u(e>>d-32,0<=e?0:-1);d=ka(z(d,b),1);if(d.equals(m(0)))return 0>b.B?m(1):m(-1);e=A(a,w(b,d));return d.add(z(e,b))}if(b.equals(q()))return m(0);if(0>a.B)return 0>b.B?z(r(a),r(b)):r(z(r(a),b));if(0>b.B)return r(z(a,r(b)));var f=m(0);for(e=a;0<=C(e,b);){d=Math.max(1,Math.floor(x(e)/x(b)));
  for(var g=Math.ceil(Math.log(d)/Math.LN2),g=48>=g?1:Math.pow(2,g-48),h=p(d),n=w(h,b);0>n.B||0<C(n,e);)d-=g,h=p(d),n=w(h,b);y(h)&&(h=m(1));f=f.add(h);e=A(e,n)}return f}function ka(a,b){if(b&=63){var d=a.H;return 32>b?u(d<<b,a.B<<b|d>>>32-b):u(0,d<<b-32)}return a}function la(a,b){if(b&=63){var d=a.B;return 32>b?u(a.H>>>b|d<<32-b,d>>>b):32==b?u(d,0):u(d>>>b-32,0)}return a}var ga=1,ha=2,ja=6;var D={w:{}};D.w.L="~";D.w.Sa="#";D.w.Z="^";D.w.wa="`";D.w.S="~#";D.v={};D.v.Qa=3;D.v.W=48;D.v.Y=44;D.v.va=D.v.Y*D.v.Y;D.v.Na=4096;D.v.Fa=function(a,b){if(a.length>D.v.Qa){if(b)return!0;var d=a.charAt(1);return a.charAt(0)===D.w.L?":"===d||"$"===d||"#"===d:!1}return!1};D.v.Da=function(a){var b=Math.floor(a/D.v.Y);a=String.fromCharCode(a%D.v.Y+D.v.W);return b?D.w.Z+String.fromCharCode(b+D.v.W)+a:D.w.Z+a};function E(){this.a=this.G=0;this.cache={}}
  E.prototype.write=function(a,b){if(D.v.Fa(a,b)){D.v.Na?this.G===D.v.va&&this.clear():(this.clear(),this.a=0,this.cache={});var d=this.cache[a];return null==d?(this.cache[a]=[D.v.Da(this.G),this.a],this.G++,a):d[1]!=this.a?(d[1]=this.a,d[0]=D.v.Da(this.G),this.G++,a):d[0]}return a};E.prototype.clear=function(){this.G=0;this.a++};D.v.writeCache=function(){return new E};D.v.ib=function(a){return a.charAt(0)===D.w.Z&&" "!==a.charAt(1)};
  D.v.Wa=function(a){return 2===a.length?a.charCodeAt(1)-D.v.W:(a.charCodeAt(1)-D.v.W)*D.v.Y+(a.charCodeAt(2)-D.v.W)};function F(){this.G=0;this.cache=[]}F.prototype.write=function(a){this.G==D.v.va&&(this.G=0);this.cache[this.G]=a;this.G++;return a};F.prototype.read=function(a){return this.cache[D.v.Wa(a)]};F.prototype.clear=function(){this.G=0};D.v.readCache=function(){return new F};D.j={};D.j.R="undefined"!=typeof Object.keys?function(a){return Object.keys(a)}:function(a){var b=[],d=0,e;for(e in a)b[d++]=e;return b};D.j.isArray="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"array"===aa(a)};D.j.za="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";D.j.Ja=function(a){return Math.round(Math.random()*a)};D.j.C=function(){return D.j.Ja(15).toString(16)};
  D.j.randomUUID=function(){var a=(8|3&D.j.Ja(14)).toString(16);return D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+"-"+D.j.C()+D.j.C()+D.j.C()+D.j.C()+"-4"+D.j.C()+D.j.C()+D.j.C()+"-"+a+D.j.C()+D.j.C()+D.j.C()+"-"+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()+D.j.C()};
  D.j.btoa=function(a){if("undefined"!=typeof btoa)return btoa(a);a=String(a);for(var b,d,e=0,f=D.j.za,g="";a.charAt(e|0)||(f="=",e%1);g+=f.charAt(63&b>>8-e%1*8)){d=a.charCodeAt(e+=.75);if(255<d)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");b=b<<8|d}return g};
  D.j.atob=function(a){if("undefined"!=typeof atob)return atob(a);a=String(a).replace(/=+$/,"");if(1==a.length%4)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");for(var b=0,d,e,f=0,g="";e=a.charAt(f++);~e&&(d=b%4?64*d+e:e,b++%4)?g+=String.fromCharCode(255&d>>(-2*b&6)):0)e=D.j.za.indexOf(e);return g};D.j.Ta=function(a){for(var b=0,d=a.length,e="",f;b<d;)f=a.subarray(b,Math.min(b+32768,d)),e+=String.fromCharCode.apply(null,f),b+=32768;return D.j.btoa(e)};
  D.j.Ma=function(a){a=D.j.atob(a);for(var b=a.length,d=new Uint8Array(b),e=0;e<b;e++)d[e]=a.charCodeAt(e);return d};D.g={};D.g.la="transit$hashCode$";D.g.Ca=1;D.g.equals=function(a,b){if(null==a)return null==b;if(a===b)return!0;if("object"===typeof a){if(D.j.isArray(a)){if(D.j.isArray(b)&&a.length===b.length){for(var d=0;d<a.length;d++)if(!D.g.equals(a[d],b[d]))return!1;return!0}return!1}if(a.M)return a.M(b);if(null!=b&&"object"===typeof b){if(b.M)return b.M(a);var d=0,e=D.j.R(b).length,f;for(f in a)if(a.hasOwnProperty(f)&&(d++,!b.hasOwnProperty(f)||!D.g.equals(a[f],b[f])))return!1;return d===e}}return!1};
  D.g.ma=function(a,b){return a^b+2654435769+(a<<6)+(a>>2)};D.g.ra={};D.g.sa=0;D.g.Ra=256;D.g.eb=function(a){var b=D.g.ra[a];if(null!=b)return b;for(var d=b=0;d<a.length;++d)b=31*b+a.charCodeAt(d),b%=4294967296;D.g.sa++;D.g.sa>=D.g.Ra&&(D.g.ra={},D.g.sa=1);return D.g.ra[a]=b};
  D.g.hashMapLike=function(a){var b=0;if(null!=a.forEach)a.forEach(function(a,d){b=(b+(D.g.o(d)^D.g.o(a)))%4503599627370496});else for(var d=D.j.R(a),e=0;e<d.length;e++)var f=d[e],g=a[f],b=(b+(D.g.o(f)^D.g.o(g)))%4503599627370496;return b};D.g.hashArrayLike=function(a){var b=0;if(D.j.isArray(a))for(var d=0;d<a.length;d++)b=D.g.ma(b,D.g.o(a[d]));else a.forEach&&a.forEach(function(a){b=D.g.ma(b,D.g.o(a))});return b};
  D.g.o=function(a){if(null==a)return 0;switch(typeof a){case "number":return a;case "boolean":return!0===a?1:0;case "string":return D.g.eb(a);case "function":var b=a[D.g.la];if(b)return b;b=D.g.Ca;"undefined"!=typeof Object.defineProperty?Object.defineProperty(a,D.g.la,{value:b,enumerable:!1}):a[D.g.la]=b;D.g.Ca++;return b;default:return a instanceof Date?a.valueOf():D.j.isArray(a)?D.g.hashArrayLike(a):a.N?a.N():D.g.hashMapLike(a)}};D.g.extendToEQ=function(a,b){a.N=b.hashCode;a.M=b.equals;return a};D.types={};"undefined"!=typeof Symbol?D.types.T=Symbol.iterator:D.types.T="@@iterator";function G(a,b){this.tag=a;this.rep=b;this.o=-1}G.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};G.prototype.a=function(a){return D.g.equals(this,a)};G.prototype.equiv=G.prototype.a;G.prototype.M=function(a){return a instanceof G?this.tag===a.tag&&D.g.equals(this.rep,a.rep):!1};G.prototype.N=function(){-1===this.o&&(this.o=D.g.ma(D.g.o(this.tag),D.g.o(this.rep)));return this.o};
  D.types.O=function(a,b){return new G(a,b)};D.types.isTaggedValue=function(a){return a instanceof G};D.types.sb=function(){return null};D.types.Ua=function(a){return"t"===a};D.types.Oa=v("9007199254740991");D.types.Pa=v("-9007199254740991");D.types.Ea=function(a){if("number"===typeof a)return a;if(a instanceof l)return a;a=v(a,10);return 0<C(a,D.types.Oa)||0>C(a,D.types.Pa)?a:x(a)};l.prototype.a=function(a){return D.g.equals(this,a)};l.prototype.equiv=l.prototype.a;
  l.prototype.M=function(a){return a instanceof l&&this.equals(a)};l.prototype.N=function(){return this.H};D.types.isInteger=function(a){return a instanceof l?!0:"number"===typeof a&&!isNaN(a)&&Infinity!==a&&parseFloat(a)===parseInt(a,10)};D.types.cb=function(a){return parseFloat(a)};D.types.ya=function(a){return D.types.O("n",a)};D.types.hb=function(a){return a instanceof G&&"n"===a.tag};D.types.xa=function(a){return D.types.O("f",a)};D.types.gb=function(a){return a instanceof G&&"f"===a.tag};
  D.types.Va=function(a){return a};function H(a){this.I=a;this.o=-1}H.prototype.toString=function(){return":"+this.I};H.prototype.namespace=function(){var a=this.I.indexOf("/");return-1!=a?this.I.substring(0,a):null};H.prototype.name=function(){var a=this.I.indexOf("/");return-1!=a?this.I.substring(a+1,this.I.length):this.I};H.prototype.a=function(a){return D.g.equals(this,a)};H.prototype.equiv=H.prototype.a;H.prototype.M=function(a){return a instanceof H&&this.I==a.I};
  H.prototype.N=function(){-1===this.o&&(this.o=D.g.o(this.I));return this.o};D.types.keyword=function(a){return new H(a)};D.types.isKeyword=function(a){return a instanceof H};function I(a){this.I=a;this.o=-1}I.prototype.namespace=function(){var a=this.I.indexOf("/");return-1!=a?this.I.substring(0,a):null};I.prototype.name=function(){var a=this.I.indexOf("/");return-1!=a?this.I.substring(a+1,this.I.length):this.I};I.prototype.toString=function(){return this.I};
  I.prototype.a=function(a){return D.g.equals(this,a)};I.prototype.equiv=I.prototype.a;I.prototype.M=function(a){return a instanceof I&&this.I==a.I};I.prototype.N=function(){-1===this.o&&(this.o=D.g.o(this.I));return this.o};D.types.symbol=function(a){return new I(a)};D.types.isSymbol=function(a){return a instanceof I};D.types.ba=function(a,b,d){var e="";d=d||b+1;for(var f=8*(7-b),g=ka(da(255),f);b<d;b++,f-=8,g=la(g,8)){var h=la(u(a.H&g.H,a.B&g.B),f).toString(16);1==h.length&&(h="0"+h);e+=h}return e};
  function J(a,b){this.a=a;this.s=b;this.o=-1}J.prototype.toString=function(){var a=this.a,b=this.s;var d=""+(D.types.ba(a,0,4)+"-");d+=D.types.ba(a,4,6)+"-";d+=D.types.ba(a,6,8)+"-";d+=D.types.ba(b,0,2)+"-";return d+=D.types.ba(b,2,8)};J.prototype.K=function(a){return D.g.equals(this,a)};J.prototype.equiv=J.prototype.K;J.prototype.M=function(a){return a instanceof J&&this.a.equals(a.a)&&this.s.equals(a.s)};J.prototype.N=function(){-1===this.o&&(this.o=D.g.o(this.toString()));return this.o};
  D.types.UUIDfromString=function(a){a=a.replace(/-/g,"");var b,d;var e=b=0;for(d=24;8>e;e+=2,d-=8)b|=parseInt(a.substring(e,e+2),16)<<d;var f=0;e=8;for(d=24;16>e;e+=2,d-=8)f|=parseInt(a.substring(e,e+2),16)<<d;var g=u(f,b);b=0;e=16;for(d=24;24>e;e+=2,d-=8)b|=parseInt(a.substring(e,e+2),16)<<d;f=0;for(d=e=24;32>e;e+=2,d-=8)f|=parseInt(a.substring(e,e+2),16)<<d;return new J(g,u(f,b))};D.types.uuid=function(a){return D.types.UUIDfromString(a)};D.types.isUUID=function(a){return a instanceof J};
  D.types.date=function(a){a="number"===typeof a?a:parseInt(a,10);return new Date(a)};D.types.qb=function(a){return new Date(a)};Date.prototype.M=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.N=function(){return this.valueOf()};D.types.binary=function(a,b){return b&&!1===b.qa||"undefined"==typeof c.X?"undefined"!=typeof Uint8Array?D.j.Ma(a):D.types.O("b",a):new c.X(a,"base64")};
  D.types.isBinary=function(a){return"undefined"!=typeof c.X&&a instanceof c.X?!0:"undefined"!=typeof Uint8Array&&a instanceof Uint8Array?!0:a instanceof G&&"b"===a.tag};D.types.uri=function(a){return D.types.O("r",a)};D.types.isURI=function(a){return a instanceof G&&"r"===a.tag};D.types.U=0;D.types.ea=1;D.types.ua=2;function K(a,b){this.entries=a;this.type=b||D.types.U;this.G=0}
  K.prototype.next=function(){if(this.G<this.entries.length){var a=null;this.type===D.types.U?a=this.entries[this.G]:this.type===D.types.ea?a=this.entries[this.G+1]:a=[this.entries[this.G],this.entries[this.G+1]];a={value:a,done:!1};this.G+=2;return a}return{value:null,done:!0}};K.prototype.next=K.prototype.next;K.prototype[D.types.T]=function(){return this};function L(a,b){this.map=a;this.type=b||D.types.U;this.keys=ma(this.map);this.G=0;this.s=null;this.a=0}
  L.prototype.next=function(){if(this.G<this.map.size){this.s&&this.a<this.s.length||(this.s=this.map.map[this.keys[this.G]],this.a=0);var a=null;this.type===D.types.U?a=this.s[this.a]:this.type===D.types.ea?a=this.s[this.a+1]:a=[this.s[this.a],this.s[this.a+1]];a={value:a,done:!1};this.G++;this.a+=2;return a}return{value:null,done:!0}};L.prototype.next=L.prototype.next;L.prototype[D.types.T]=function(){return this};
  D.types.oa=function(a,b){if(a instanceof M&&D.types.isMap(b)){if(a.size!==b.size)return!1;for(var d in a.map)for(var e=a.map[d],f=0;f<e.length;f+=2)if(!D.g.equals(e[f+1],b.get(e[f])))return!1;return!0}if(a instanceof N&&D.types.isMap(b)){if(a.size!==b.size)return!1;d=a.D;for(f=0;f<d.length;f+=2)if(!D.g.equals(d[f+1],b.get(d[f])))return!1;return!0}if(null!=b&&"object"===typeof b&&(f=D.j.R(b),d=f.length,a.size===d)){for(e=0;e<d;e++){var g=f[e];if(!a.has(g)||!D.g.equals(b[g],a.get(g)))return!1}return!0}return!1};
  D.types.ia=8;D.types.ta=32;D.types.La=32;D.types.print=function(a){return null==a?"null":"array"==aa(a)?"["+a.toString()+"]":"string"==typeof a?'"'+a+'"':a.toString()};D.types.Ia=function(a){var b=0,d="TransitMap {";a.forEach(function(e,f){d+=D.types.print(f)+" => "+D.types.print(e);b<a.size-1&&(d+=", ");b++});return d+"}"};D.types.nb=function(a){var b=0,d="TransitSet {";a.forEach(function(e){d+=D.types.print(e);b<a.size-1&&(d+=", ");b++});return d+"}"};
  function N(a){this.D=a;this.A=null;this.o=-1;this.size=a.length/2;this.a=0}N.prototype.toString=function(){return D.types.Ia(this)};N.prototype.inspect=function(){return this.toString()};function na(a){if(a.A)throw Error("Invalid operation, already converted");if(a.size<D.types.ia)return!1;a.a++;return a.a>D.types.La?(a.A=D.types.map(a.D,!1,!0),a.D=[],!0):!1}N.prototype.clear=function(){this.o=-1;this.A?this.A.clear():this.D=[];this.size=0};N.prototype.clear=N.prototype.clear;
  N.prototype.keys=function(){return this.A?this.A.keys():new K(this.D,D.types.U)};N.prototype.keys=N.prototype.keys;N.prototype.s=function(){if(this.A)return this.A.s();for(var a=[],b=0,d=0;d<this.D.length;b++,d+=2)a[b]=this.D[d];return a};N.prototype.keySet=N.prototype.s;N.prototype.entries=function(){return this.A?this.A.entries():new K(this.D,D.types.ua)};N.prototype.entries=N.prototype.entries;N.prototype.values=function(){return this.A?this.A.values():new K(this.D,D.types.ea)};
  N.prototype.values=N.prototype.values;N.prototype.forEach=function(a){if(this.A)this.A.forEach(a);else for(var b=0;b<this.D.length;b+=2)a(this.D[b+1],this.D[b])};N.prototype.forEach=N.prototype.forEach;N.prototype.get=function(a,b){if(this.A)return this.A.get(a);if(na(this))return this.get(a);for(var d=0;d<this.D.length;d+=2)if(D.g.equals(this.D[d],a))return this.D[d+1];return b};N.prototype.get=N.prototype.get;
  N.prototype.has=function(a){if(this.A)return this.A.has(a);if(na(this))return this.has(a);for(var b=0;b<this.D.length;b+=2)if(D.g.equals(this.D[b],a))return!0;return!1};N.prototype.has=N.prototype.has;N.prototype.set=function(a,b){this.o=-1;if(this.A)this.A.set(a,b),this.size=this.A.size;else{for(var d=0;d<this.D.length;d+=2)if(D.g.equals(this.D[d],a)){this.D[d+1]=b;return}this.D.push(a);this.D.push(b);this.size++;this.size>D.types.ta&&(this.A=D.types.map(this.D,!1,!0),this.D=null)}};
  N.prototype.set=N.prototype.set;N.prototype["delete"]=function(a){this.o=-1;if(this.A)return a=this.A["delete"](a),this.size=this.A.size,a;for(var b=0;b<this.D.length;b+=2)if(D.g.equals(this.D[b],a))return a=this.D[b+1],this.D.splice(b,2),this.size--,a};N.prototype.K=function(){var a=D.types.map();this.forEach(function(b,d){a.set(d,b)});return a};N.prototype.clone=N.prototype.K;N.prototype[D.types.T]=function(){return this.entries()};
  N.prototype.N=function(){if(this.A)return this.A.N();-1===this.o&&(this.o=D.g.hashMapLike(this));return this.o};N.prototype.M=function(a){return this.A?D.types.oa(this.A,a):D.types.oa(this,a)};function M(a,b,d){this.map=b||{};this.a=a||[];this.size=d||0;this.o=-1}M.prototype.toString=function(){return D.types.Ia(this)};M.prototype.inspect=function(){return this.toString()};M.prototype.clear=function(){this.o=-1;this.map={};this.a=[];this.size=0};M.prototype.clear=M.prototype.clear;
  function ma(a){return a.a?a.a:D.j.R(a.map)}M.prototype["delete"]=function(a){this.o=-1;this.a=null;for(var b=D.g.o(a),d=this.map[b],e=0;e<d.length;e+=2)if(D.g.equals(a,d[e]))return a=d[e+1],d.splice(e,2),0===d.length&&delete this.map[b],this.size--,a};M.prototype.entries=function(){return new L(this,D.types.ua)};M.prototype.entries=M.prototype.entries;M.prototype.forEach=function(a){for(var b=ma(this),d=0;d<b.length;d++)for(var e=this.map[b[d]],f=0;f<e.length;f+=2)a(e[f+1],e[f],this)};
  M.prototype.forEach=M.prototype.forEach;M.prototype.get=function(a,b){var d=D.g.o(a),d=this.map[d];if(null!=d)for(var e=0;e<d.length;e+=2){if(D.g.equals(a,d[e]))return d[e+1]}else return b};M.prototype.get=M.prototype.get;M.prototype.has=function(a){var b=D.g.o(a),b=this.map[b];if(null!=b)for(var d=0;d<b.length;d+=2)if(D.g.equals(a,b[d]))return!0;return!1};M.prototype.has=M.prototype.has;M.prototype.keys=function(){return new L(this,D.types.U)};M.prototype.keys=M.prototype.keys;
  M.prototype.s=function(){for(var a=ma(this),b=[],d=0;d<a.length;d++)for(var e=this.map[a[d]],f=0;f<e.length;f+=2)b.push(e[f]);return b};M.prototype.keySet=M.prototype.s;M.prototype.set=function(a,b){this.o=-1;var d=D.g.o(a),e=this.map[d];if(null==e)this.a&&this.a.push(d),this.map[d]=[a,b],this.size++;else{for(var d=!0,f=0;f<e.length;f+=2)if(D.g.equals(b,e[f])){d=!1;e[f]=b;break}d&&(e.push(a),e.push(b),this.size++)}};M.prototype.set=M.prototype.set;M.prototype.values=function(){return new L(this,D.types.ea)};
  M.prototype.values=M.prototype.values;M.prototype.K=function(){var a=D.types.map();this.forEach(function(b,d){a.set(d,b)});return a};M.prototype.clone=M.prototype.K;M.prototype[D.types.T]=function(){return this.entries()};M.prototype.N=function(){-1===this.o&&(this.o=D.g.hashMapLike(this));return this.o};M.prototype.M=function(a){return D.types.oa(this,a)};
  D.types.map=function(a,b,d){a=a||[];b=!1===b?b:!0;if((!0!==d||!d)&&a.length<=2*D.types.ta){if(b){var e=a;a=[];for(b=0;b<e.length;b+=2){var f=!1;for(d=0;d<a.length;d+=2)if(D.g.equals(a[d],e[b])){a[d+1]=e[b+1];f=!0;break}f||(a.push(e[b]),a.push(e[b+1]))}}return new N(a)}var e={},f=[],g=0;for(b=0;b<a.length;b+=2){d=D.g.o(a[b]);var h=e[d];if(null==h)f.push(d),e[d]=[a[b],a[b+1]],g++;else{var n=!0;for(d=0;d<h.length;d+=2)if(D.g.equals(h[d],a[b])){h[d+1]=a[b+1];n=!1;break}n&&(h.push(a[b]),h.push(a[b+1]),
  g++)}}return new M(f,e,g)};D.types.fb=function(a){return a instanceof N};D.types.isMap=function(a){return a instanceof N||a instanceof M};function P(a){this.map=a;this.size=a.size}P.prototype.toString=function(){return D.types.nb(this)};P.prototype.inspect=function(){return this.toString()};P.prototype.add=function(a){this.map.set(a,a);this.size=this.map.size};P.prototype.add=P.prototype.add;P.prototype.clear=function(){this.map=new M;this.size=0};P.prototype.clear=P.prototype.clear;
  P.prototype["delete"]=function(a){a=this.map["delete"](a);this.size=this.map.size;return a};P.prototype.entries=function(){return this.map.entries()};P.prototype.entries=P.prototype.entries;P.prototype.forEach=function(a){var b=this;this.map.forEach(function(d,e){a(e,b)})};P.prototype.forEach=P.prototype.forEach;P.prototype.has=function(a){return this.map.has(a)};P.prototype.has=P.prototype.has;P.prototype.keys=function(){return this.map.keys()};P.prototype.keys=P.prototype.keys;P.prototype.s=function(){return this.map.s()};
  P.prototype.keySet=P.prototype.s;P.prototype.values=function(){return this.map.values()};P.prototype.values=P.prototype.values;P.prototype.a=function(){var a=D.types.set();this.forEach(function(b){a.add(b)});return a};P.prototype.clone=P.prototype.a;P.prototype[D.types.T]=function(){return this.values()};P.prototype.M=function(a){if(a instanceof P){if(this.size===a.size)return D.g.equals(this.map,a.map)}else return!1};P.prototype.N=function(){return D.g.o(this.map)};
  D.types.set=function(a){a=a||[];for(var b={},d=[],e=0,f=0;f<a.length;f++){var g=D.g.o(a[f]),h=b[g];if(null==h)d.push(g),b[g]=[a[f],a[f]],e++;else{for(var g=!0,n=0;n<h.length;n+=2)if(D.g.equals(h[n],a[f])){g=!1;break}g&&(h.push(a[f]),h.push(a[f]),e++)}}return new P(new M(d,b,e))};D.types.isSet=function(a){return a instanceof P};D.types.quoted=function(a){return D.types.O("'",a)};D.types.isQuoted=function(a){return a instanceof G&&"'"===a.tag};D.types.list=function(a){return D.types.O("list",a)};
  D.types.isList=function(a){return a instanceof G&&"list"===a.tag};D.types.link=function(a){return D.types.O("link",a)};D.types.isLink=function(a){return a instanceof G&&"link"===a.tag};D.types.ob=function(a){switch(a){case "-INF":return-Infinity;case "INF":return Infinity;case "NaN":return NaN;default:throw Error("Invalid special double value "+a);}};D.l={};D.l.Aa=0;D.l.ja="transit$guid$"+D.j.randomUUID();D.l.Ka=function(a){if(null==a)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a[D.l.ja];null==b&&("undefined"!=typeof Object.defineProperty?(b=++D.l.Aa,Object.defineProperty(a,D.l.ja,{value:b,enumerable:!1})):a[D.l.ja]=b=++D.l.Aa);return b};D.l.constructor=function(a){return null==a?null:a.constructor};
  D.l.V=function(a,b){for(var d=a.toString(),e=d.length;e<b;e++)d="0"+d;return d};D.l.stringableKeys=function(a){a=D.j.R(a);for(var b=0;b<a.length;b++);return!0};function Q(){}Q.prototype.tag=function(){return"_"};Q.prototype.rep=function(){return null};Q.prototype.J=function(){return"null"};function R(){}R.prototype.tag=function(){return"s"};R.prototype.rep=function(a){return a};R.prototype.J=function(a){return a};function oa(){}oa.prototype.tag=function(){return"i"};oa.prototype.rep=function(a){return a};
  oa.prototype.J=function(a){return a.toString()};function pa(){}pa.prototype.tag=function(){return"i"};pa.prototype.rep=function(a){return a.toString()};pa.prototype.J=function(a){return a.toString()};function qa(){}qa.prototype.tag=function(){return"?"};qa.prototype.rep=function(a){return a};qa.prototype.J=function(a){return a.toString()};function sa(){}sa.prototype.tag=function(){return"array"};sa.prototype.rep=function(a){return a};sa.prototype.J=function(){return null};function ta(){}
  ta.prototype.tag=function(){return"map"};ta.prototype.rep=function(a){return a};ta.prototype.J=function(){return null};function ua(){}ua.prototype.tag=function(){return"t"};ua.prototype.rep=function(a){return a.getUTCFullYear()+"-"+D.l.V(a.getUTCMonth()+1,2)+"-"+D.l.V(a.getUTCDate(),2)+"T"+D.l.V(a.getUTCHours(),2)+":"+D.l.V(a.getUTCMinutes(),2)+":"+D.l.V(a.getUTCSeconds(),2)+"."+D.l.V(a.getUTCMilliseconds(),3)+"Z"};ua.prototype.J=function(a,b){return b.rep(a)};function S(){}S.prototype.tag=function(){return"m"};
  S.prototype.rep=function(a){return a.valueOf()};S.prototype.J=function(a){return a.valueOf().toString()};S.prototype.Ba=function(){return new ua};function va(){}va.prototype.tag=function(){return"u"};va.prototype.rep=function(a){return a.toString()};va.prototype.J=function(a){return a.toString()};function wa(){}wa.prototype.tag=function(){return":"};wa.prototype.rep=function(a){return a.I};wa.prototype.J=function(a,b){return b.rep(a)};function xa(){}xa.prototype.tag=function(){return"$"};
  xa.prototype.rep=function(a){return a.I};xa.prototype.J=function(a,b){return b.rep(a)};function za(){}za.prototype.tag=function(a){return a.tag};za.prototype.rep=function(a){return a.rep};za.prototype.J=function(){return null};function Aa(){}Aa.prototype.tag=function(){return"set"};Aa.prototype.rep=function(a){var b=[];a.forEach(function(a){b.push(a)});return D.types.O("array",b)};Aa.prototype.J=function(){return null};function Ba(){}Ba.prototype.tag=function(){return"map"};Ba.prototype.rep=function(a){return a};
  Ba.prototype.J=function(){return null};function Ca(){}Ca.prototype.tag=function(){return"map"};Ca.prototype.rep=function(a){return a};Ca.prototype.J=function(){return null};function Da(){}Da.prototype.tag=function(){return"b"};Da.prototype.rep=function(a){return a.toString("base64")};Da.prototype.J=function(){return null};function Ea(){}Ea.prototype.tag=function(){return"b"};Ea.prototype.rep=function(a){return D.j.Ta(a)};Ea.prototype.J=function(){return null};
  D.l.Xa=function(a){a.set(null,new Q);a.set(String,new R);a.set(Number,new oa);a.set(l,new pa);a.set(Boolean,new qa);a.set(Array,new sa);a.set(Object,new ta);a.set(Date,new S);a.set(J,new va);a.set(H,new wa);a.set(I,new xa);a.set(G,new za);a.set(P,new Aa);a.set(N,new Ba);a.set(M,new Ca);"undefined"!=typeof c.X&&a.set(c.X,new Da);"undefined"!=typeof Uint8Array&&a.set(Uint8Array,new Ea)};function T(){this.l={};D.l.Xa(this)}
  T.prototype.get=function(a){a="string"===typeof a?this.l[a]:this.l[D.l.Ka(a)];return null!=a?a:this.l["default"]};T.prototype.get=T.prototype.get;D.l.pb=function(a){switch(a){case "null":case "string":case "boolean":case "number":case "array":case "map":return!1}return!0};T.prototype.set=function(a,b){"string"===typeof a&&D.l.pb(a)?this.l[a]=b:this.l[D.l.Ka(a)]=b};D.h={};D.h.decoder={};function Fa(a){this.ga=a}D.h.decoder.tag=function(a){return new Fa(a)};D.h.decoder.Ga=function(a){return a&&a instanceof Fa};D.h.decoder.kb=function(a){switch(a){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":return!0}return!1};
  function W(a){this.K=a||{};this.l={};for(var b in this.ca.l)this.l[b]=this.ca.l[b];for(b in this.K.handlers){if(D.h.decoder.kb(b))throw Error('Cannot override handler for ground type "'+b+'"');this.l[b]=this.K.handlers[b]}this.fa=null!=this.K.preferStrings?this.K.preferStrings:this.ca.fa;this.qa=null!=this.K.preferBuffers?this.K.preferBuffers:this.ca.qa;this.ka=this.K.defaultHandler||this.ca.ka;this.s=this.K.mapBuilder;this.P=this.K.arrayBuilder}
  W.prototype.ca={l:{_:function(){return null},"?":function(a){return D.types.Ua(a)},b:function(a,b){return D.types.binary(a,b)},i:function(a){return D.types.Ea(a)},n:function(a){return D.types.ya(a)},d:function(a){return D.types.cb(a)},f:function(a){return D.types.xa(a)},c:function(a){return D.types.Va(a)},":":function(a){return D.types.keyword(a)},$:function(a){return D.types.symbol(a)},r:function(a){return D.types.uri(a)},z:function(a){return D.types.ob(a)},"'":function(a){return a},m:function(a){return D.types.date(a)},
  t:function(a){return D.types.qb(a)},u:function(a){return D.types.uuid(a)},set:function(a){return D.types.set(a)},list:function(a){return D.types.list(a)},link:function(a){return D.types.link(a)},cmap:function(a){return D.types.map(a,!1)}},ka:function(a,b){return D.types.O(a,b)},fa:!0,qa:!0};
  W.prototype.a=function(a,b,d,e){if(null==a)return null;switch(typeof a){case "string":return D.v.Fa(a,d)?(a=Ga(this,a),b&&b.write(a,d),b=a):b=D.v.ib(a)?b.read(a,d):Ga(this,a),b;case "object":if(D.j.isArray(a))if("^ "===a[0])if(this.s)if(a.length<2*D.types.ia+1&&this.s.fromArray){e=[];for(d=1;d<a.length;d+=2)e.push(this.a(a[d],b,!0,!1)),e.push(this.a(a[d+1],b,!1,!1));b=this.s.fromArray(e,a)}else{e=this.s.init(a);for(d=1;d<a.length;d+=2)e=this.s.add(e,this.a(a[d],b,!0,!1),this.a(a[d+1],b,!1,!1),a);
  b=this.s.finalize(e,a)}else{e=[];for(d=1;d<a.length;d+=2)e.push(this.a(a[d],b,!0,!1)),e.push(this.a(a[d+1],b,!1,!1));b=D.types.map(e,!1)}else b=Ha(this,a,b,d,e);else{d=D.j.R(a);var f=d[0];e=1==d.length?this.a(f,b,!1,!1):null;if(D.h.decoder.Ga(e))a=a[f],d=this.l[e.ga],b=null!=d?d(this.a(a,b,!1,!0),this):D.types.O(e.ga,this.a(a,b,!1,!1));else if(this.s)if(d.length<2*D.types.ia&&this.s.fromArray){var g=[];for(f=0;f<d.length;f++)e=d[f],g.push(this.a(e,b,!0,!1)),g.push(this.a(a[e],b,!1,!1));b=this.s.fromArray(g,
  a)}else{g=this.s.init(a);for(f=0;f<d.length;f++)e=d[f],g=this.s.add(g,this.a(e,b,!0,!1),this.a(a[e],b,!1,!1),a);b=this.s.finalize(g,a)}else{g=[];for(f=0;f<d.length;f++)e=d[f],g.push(this.a(e,b,!0,!1)),g.push(this.a(a[e],b,!1,!1));b=D.types.map(g,!1)}}return b}return a};W.prototype.decode=W.prototype.a;
  function Ha(a,b,d,e,f){if(f){var g=[];for(f=0;f<b.length;f++)g.push(a.a(b[f],d,e,!1));return g}g=d&&d.G;if(2===b.length&&"string"===typeof b[0]&&(f=a.a(b[0],d,!1,!1),D.h.decoder.Ga(f)))return g=b[1],b=a.l[f.ga],null!=b?g=b(a.a(g,d,e,!0),a):D.types.O(f.ga,a.a(g,d,e,!1));d&&g!=d.G&&(d.G=g);if(a.P){if(32>=b.length&&a.P.fromArray){g=[];for(f=0;f<b.length;f++)g.push(a.a(b[f],d,e,!1));return a.P.fromArray(g,b)}g=a.P.init(b);for(f=0;f<b.length;f++)g=a.P.add(g,a.a(b[f],d,e,!1),b);return a.P.finalize(g,b)}g=
  [];for(f=0;f<b.length;f++)g.push(a.a(b[f],d,e,!1));return g}function Ga(a,b){if(b.charAt(0)===D.w.L){var d=b.charAt(1);if(d===D.w.L||d===D.w.Z||d===D.w.wa)return b.substring(1);if(d===D.w.Sa)return D.h.decoder.tag(b.substring(2));var e=a.l[d];return null==e?a.ka(d,b.substring(2)):e(b.substring(2),a)}return b}D.h.decoder.decoder=function(a){return new W(a)};D.h.reader={};function Ia(a){this.decoder=new W(a)}function Ja(a,b){this.s=a;this.a=b||{};this.cache=this.a.cache?this.a.cache:new F}Ja.prototype.read=function(a){var b=this.cache;a=this.s.decoder.a(JSON.parse(a),b);this.cache.clear();return a};Ja.prototype.read=Ja.prototype.read;D.h.writer={};D.h.writer.escape=function(a){if(0<a.length){var b=a.charAt(0);return b===D.w.L||b===D.w.Z||b===D.w.wa?D.w.L+a:a}return a};
  function Ka(a){this.a=a||{};this.fa=null!=this.a.preferStrings?this.a.preferStrings:!0;this.Ha=this.a.objectBuilder||null;this.transform=this.a.transform||null;this.l=new T;if(a=this.a.handlers){if(D.j.isArray(a)||!a.forEach)throw Error('transit writer "handlers" option must be a map');var b=this;a.forEach(function(a,e){if(void 0!==e)b.l.set(e,a);else throw Error("Cannot create handler for JavaScript undefined");})}this.aa=this.a.handlerForForeign;this.ha=this.a.unpack||function(a){return D.types.fb(a)&&
  null===a.A?a.D:!1};this.da=this.a&&this.a.verbose||!1}function La(a,b){var d=a.l.get(D.l.constructor(b));return null!=d?d:(d=b&&b.transitTag)?a.l.get(d):null}function Y(a,b,d,e,f){a=a+b+d;return f?f.write(a,e):a}D.h.writer.ab=function(a,b,d){var e=[];if(D.j.isArray(b))for(var f=0;f<b.length;f++)e.push(D.h.writer.F(a,b[f],!1,d));else b.forEach(function(b){e.push(D.h.writer.F(a,b,!1,d))});return e};D.h.writer.Ya=function(a,b,d){return D.h.writer.ab(a,b,d)};
  D.h.writer.na=function(a,b){if("string"!==typeof b){var d=La(a,b);return d&&1===d.tag(b).length}return!0};
  D.h.writer.stringableKeys=function(a,b){var d=a.ha(b),e=!0;if(d){for(var f=0;f<d.length&&(e=D.h.writer.na(a,d[f]),e);f+=2);return e}if(b.keys&&(d=b.keys(),f=null,d.next)){for(f=d.next();!f.done;){e=D.h.writer.na(a,f.value);if(!e)break;f=d.next()}return e}if(b.forEach)return b.forEach(function(b,d){e=e&&D.h.writer.na(a,d)}),e;throw Error("Cannot walk keys of object type "+D.l.constructor(b).name);};
  D.h.writer.jb=function(a){if(a.constructor.transit$isObject)return!0;var b=a.constructor.toString(),b=b.substr(9),b=b.substr(0,b.indexOf("(")),b="Object"==b;"undefined"!=typeof Object.defineProperty?Object.defineProperty(a.constructor,"transit$isObject",{value:b,enumerable:!1}):a.constructor.transit$isObject=b;return b};
  D.h.writer.$a=function(a,b,d){var e=null,f=null,g=null,e=null,h=0;if(b.constructor===Object||null!=b.forEach||a.aa&&D.h.writer.jb(b)){if(a.da){if(null!=b.forEach){if(D.h.writer.stringableKeys(a,b)){var n={};b.forEach(function(b,e){n[D.h.writer.F(a,e,!0,!1)]=D.h.writer.F(a,b,!1,d)});return n}e=a.ha(b);f=[];g=Y(D.w.S,"cmap","",!0,d);if(e)for(;h<e.length;h+=2)f.push(D.h.writer.F(a,e[h],!1,!1)),f.push(D.h.writer.F(a,e[h+1],!1,d));else b.forEach(function(b,e){f.push(D.h.writer.F(a,e,!1,!1));f.push(D.h.writer.F(a,
  b,!1,d))});n={};n[g]=f;return n}e=D.j.R(b);for(n={};h<e.length;h++)n[D.h.writer.F(a,e[h],!0,!1)]=D.h.writer.F(a,b[e[h]],!1,d);return n}if(null!=b.forEach){if(D.h.writer.stringableKeys(a,b)){e=a.ha(b);n=["^ "];if(e)for(;h<e.length;h+=2)n.push(D.h.writer.F(a,e[h],!0,d)),n.push(D.h.writer.F(a,e[h+1],!1,d));else b.forEach(function(b,e){n.push(D.h.writer.F(a,e,!0,d));n.push(D.h.writer.F(a,b,!1,d))});return n}e=a.ha(b);f=[];g=Y(D.w.S,"cmap","",!0,d);if(e)for(;h<e.length;h+=2)f.push(D.h.writer.F(a,e[h],
  !1,d)),f.push(D.h.writer.F(a,e[h+1],!1,d));else b.forEach(function(b,e){f.push(D.h.writer.F(a,e,!1,d));f.push(D.h.writer.F(a,b,!1,d))});return[g,f]}n=["^ "];for(e=D.j.R(b);h<e.length;h++)n.push(D.h.writer.F(a,e[h],!0,d)),n.push(D.h.writer.F(a,b[e[h]],!1,d));return n}if(null!=a.Ha)return a.Ha(b,function(b){return D.h.writer.F(a,b,!0,d)},function(b){return D.h.writer.F(a,b,!1,d)});h=D.l.constructor(b).name;e=Error("Cannot write "+h);e.data={pa:b,type:h};throw e;};
  D.h.writer.bb=function(a,b,d,e){if(a.da){var f={};f[Y(D.w.S,b,"",!0,e)]=D.h.writer.F(a,d,!1,e);return f}return[Y(D.w.S,b,"",!0,e),D.h.writer.F(a,d,!1,e)]};D.h.writer.Za=function(a,b,d,e,f,g,h){if(1===d.length){if("string"===typeof e)return Y(D.w.L,d,e,g,h);if(g||a.fa){(e=a.da&&b.Ba())?(d=e.tag(f),e=e.J(f,e)):e=b.J(f,b);if(null!==e)return Y(D.w.L,d,e,g,h);b=Error('Tag "'+d+'" cannot be encoded as string');b.data={tag:d,rep:e,pa:f};throw b;}}return D.h.writer.bb(a,d,e,h)};
  D.h.writer.F=function(a,b,d,e){null!==a.transform&&(b=a.transform(b));var f=La(a,b)||(a.aa?a.aa(b,a.l):null),g=f?f.tag(b):null,h=f?f.rep(b):null;if(null!=f&&null!=g)switch(g){case "_":return d?Y(D.w.L,"_","",d,e):null;case "s":return Y("","",D.h.writer.escape(h),d,e);case "?":return d?Y(D.w.L,"?",h.toString()[0],d,e):h;case "i":return Infinity===h?Y(D.w.L,"z","INF",d,e):-Infinity===h?Y(D.w.L,"z","-INF",d,e):isNaN(h)?Y(D.w.L,"z","NaN",d,e):d||"string"===typeof h||h instanceof l?Y(D.w.L,"i",h.toString(),
  d,e):h;case "d":return d?Y(h.L,"d",h,d,e):h;case "b":return Y(D.w.L,"b",h,d,e);case "'":return a.da?(b={},d=Y(D.w.S,"'","",!0,e),b[d]=D.h.writer.F(a,h,!1,e),a=b):a=[Y(D.w.S,"'","",!0,e),D.h.writer.F(a,h,!1,e)],a;case "array":return D.h.writer.Ya(a,h,e);case "map":return D.h.writer.$a(a,h,e);default:return D.h.writer.Za(a,f,g,h,b,d,e)}else throw a=D.l.constructor(b).name,e=Error("Cannot write "+a),e.data={pa:b,type:a},e;};
  D.h.writer.mb=function(a,b){var d=La(a,b)||(a.aa?a.aa(b,a.l):null);if(null!=d)return 1===d.tag(b).length?D.types.quoted(b):b;var d=D.l.constructor(b).name,e=Error("Cannot write "+d);e.data={pa:b,type:d};throw e;};D.h.writer.lb=function(a,b,d,e){return JSON.stringify(D.h.writer.F(a,D.h.writer.mb(a,b),d,e))};function Z(a,b){this.a=a;this.s=b||{};!1===this.s.cache?this.cache=null:this.cache=this.s.cache?this.s.cache:new E}Z.prototype.P=function(){return this.a};Z.prototype.marshaller=Z.prototype.P;
  Z.prototype.write=function(a,b){var d=b||{};var e=d.asMapKey||!1,f=this.a.da?!1:this.cache;d=!1===d.marshalTop?D.h.writer.F(this.a,a,e,f):D.h.writer.lb(this.a,a,e,f);null!=this.cache&&this.cache.clear();return d};Z.prototype.write=Z.prototype.write;Z.prototype.K=function(a,b){this.a.l.set(a,b)};Z.prototype.register=Z.prototype.K;D.reader=function(a,b){if("json"===a||"json-verbose"===a||null==a){var d=new Ia(b);return new Ja(d,b)}throw Error("Cannot create reader of type "+a);};D.writer=function(a,b){if("json"===a||"json-verbose"===a||null==a){"json-verbose"===a&&(b||(b={}),b.verbose=!0);var d=new Ka(b);return new Z(d,b)}d=Error('Type must be "json"');d.data={type:a};throw d;};
  D.makeWriteHandler=function(a){function b(){}b.prototype.tag=a.tag;b.prototype.rep=a.rep;b.prototype.J=a.stringRep;b.prototype.Ba=a.getVerboseHandler;return new b};D.makeBuilder=function(a){function b(){}b.prototype.init=a.init;b.prototype.add=a.add;b.prototype.finalize=a.finalize;b.prototype.fromArray=a.fromArray;return new b};D.date=D.types.date;D.integer=D.types.Ea;D.isInteger=D.types.isInteger;D.uuid=D.types.uuid;D.isUUID=D.types.isUUID;D.bigInt=D.types.ya;D.isBigInt=D.types.hb;D.bigDec=D.types.xa;
  D.isBigDec=D.types.gb;D.keyword=D.types.keyword;D.isKeyword=D.types.isKeyword;D.symbol=D.types.symbol;D.isSymbol=D.types.isSymbol;D.binary=D.types.binary;D.isBinary=D.types.isBinary;D.uri=D.types.uri;D.isURI=D.types.isURI;D.map=D.types.map;D.isMap=D.types.isMap;D.set=D.types.set;D.isSet=D.types.isSet;D.list=D.types.list;D.isList=D.types.isList;D.quoted=D.types.quoted;D.isQuoted=D.types.isQuoted;D.tagged=D.types.O;D.isTaggedValue=D.types.isTaggedValue;D.link=D.types.link;D.isLink=D.types.isLink;
  D.hash=D.g.o;D.hashMapLike=D.g.hashMapLike;D.hashArrayLike=D.g.hashArrayLike;D.equals=D.g.equals;D.extendToEQ=D.g.extendToEQ;D.mapToObject=function(a){var b={};a.forEach(function(a,e){if("string"!==typeof e)throw Error("Cannot convert map with non-string keys");b[e]=a});return b};D.objectToMap=function(a){var b=D.map(),d;for(d in a)a.hasOwnProperty(d)&&b.set(d,a[d]);return b};D.decoder=D.h.decoder.decoder;D.readCache=D.v.readCache;D.writeCache=D.v.writeCache;D.UUIDfromString=D.types.UUIDfromString;
  D.randomUUID=D.j.randomUUID;D.stringableKeys=D.h.writer.stringableKeys;D.rb={};define("transit",[],function(){return D});})();
