version: 2
updates:
  # Enable npm updates for all of our package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "one app"
    allow:
      - dependency-type: "direct"
    target-branch: "main"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "docker"
      - "dependabot"
    target-branch: "main"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
      - "dependabot"
    target-branch: "main"
