version: 2
updates:
  # Enable npm updates for all of our package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "one app"
    allow:
      - dependency-type: "direct"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/cultured-frankie/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "cultured frankie v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/cultured-frankie/0.0.1"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "cultured frankie v0.0.1"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/frank-lloyd-root/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "frank lloyd root v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/frank-lloyd-root/0.0.1"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "frank lloyd root v0.0.1"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/frank-lloyd-root/0.0.2"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "frank lloyd root v0.0.2"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/frank-lloyd-root/0.0.3"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "frank lloyd root v0.0.3"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/frank-the-parrot/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "frank the parrot v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/franks-burgers/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "franks burgers v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/healthy-frank/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "healthy frank v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/late-frank/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "late frank v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/late-frank/0.0.1"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "late frank v0.0.1"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/late-frank/0.0.2"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "late frank v0.0.2"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/needy-frank/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "needy frank v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/needy-frank/0.0.1"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "needy frank v0.0.1"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/picky-frank/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "picky frank v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/picky-frank/0.0.1"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "picky frank v0.0.1"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/preview-frank/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "preview frank v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/ssr-frank/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "ssr frank v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/vitruvius-franklin/0.0.0"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "vitruvius franklin v0.0.0"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/prod-samples/sample-modules/vitruvius-franklin/0.0.1"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
      - "prod samples"
      - "vitruvius franklin v0.0.1"
    allow:
      - dependency-type: "production"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "docker"
      - "dependabot"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
      - "dependabot"
