feature:
- head-branch: ['feature/*', 'feat/*']
fix:
- head-branch: ['fix/*', 'bug/*']
chore:
- head-branch: chore/*
documentation:
- head-branch: docs/*
refactor:
- head-branch: refactor/*
test:
- head-branch: test/*
