receivers:
  otlp:
    protocols:
      grpc:
processors:
  batch:
exporters:      
  logging:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
