receivers:
  otlp:
    protocols:
      grpc:
exporters:      
  file/traces:
    path: ./traces.jsonl
    append: true
  file/logs:
    path: ./logs.jsonl
    append: true
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [file/logs]
    traces:
      receivers: [otlp]
      exporters: [file/traces]
