receivers:
  otlp:
    protocols:
      grpc:
exporters:      
  logging:
    verbosity: detailed
  file:
    path: /tmp/traces.jsonl
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      exporters: [file]
