{
 "title": "One App Classic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "granularity", "label": "Rate Granularity:", "query": "2m, 10m, 30m, 1h, 6h, 1d, 7d" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node.Js",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_version_info",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Version",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds"
    }
   ]
  },
  {
   "title": "Module Map Load Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(oneapp_holocron_module_map_poll_consecutive_errors_total[$granularity])",
     "legendFormat": "{{podname}}"
    }
   ]
  },
  {
   "title": "Module Map Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oneapp_holocron_module_map_poll_restarted_total[$granularity])"
    }
   ]
  },
  {
   "title": "Module Map Updated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oneapp_holocron_module_map_updated_total[$granularity])"
    }
   ]
  },
  {
   "title": "Module Map Poll Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oneapp_holocron_module_map_poll_total[$granularity])",
     "legendFormat": "{{podname}}"
    }
   ]
  },
  {
   "title": "GC Runs rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nodejs_gc_duration_seconds_bucket[30s])) by (le))",
     "legendFormat": "{{gctype}} {{podname}}"
    }
   ]
  },
  {
   "title": "Circuit Events, Opening and Closing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(circuit{event=~\"open|close\"}[2m])",
     "legendFormat": "{{name}} {{event}} ({{podname}})"
    }
   ]
  },
  {
   "title": "Language Pack Server Cache",
   "type": "graph",
   "description": "Estimated size of the language pack cache on the server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "oneapp_intl_cache_size_total",
     "legendFormat": "Server Langpack cache: {{podname}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Heap Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes",
     "legendFormat": "Total heap {{space}}: {{podname}}"
    },
    {
     "expr": "nodejs_heap_space_size_used_bytes",
     "legendFormat": "Used heap {{space}}: {{podname}}"
    },
    {
     "expr": "nodejs_heap_space_size_used_bytes",
     "legendFormat": "Available heap {{space}}: {{podname}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Process RSS: {{podname}}" }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Total Heap: {{podname}}" },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Used Heap: {{podname}}" },
    { "expr": "process_heap_bytes", "legendFormat": "Process heap" },
    { "expr": "nodejs_external_memory_bytes", "legendFormat": "External Memory: {{podname}}" }
   ]
  },
  { "title": "Event Loop", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "eventloop lag: {{podname}}" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$granularity])*100",
     "legendFormat": "Process CPU: {{podname}}"
    }
   ]
  },
  { "title": "Circuit Breaker Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Circuit Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(circuit[$granularity])",
     "legendFormat": "{{name}} {{event}} ({{podname}})"
    }
   ]
  },
  {
   "title": "Circuit Perf: getModuleData",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "rate(circuit_perf{name=\"getModuleData\"}[$granularity])"
    }
   ]
  }
 ]
}