name: auto-merge

on:
  pull_request:
    branches:
      - [dependabot-changes]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.3
        with:
          github-token: ${{ secrets.PA_TOKEN }}
          command: "squash and merge"
          approve: true
          target: minor
