name: "[on PR] One App Integration Tests"
on: pull_request
jobs:
  one-app-integration-pr:
    name:  One App Integration Tests - PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: npm install
        run: npm ci
        env:
          NODE_ENV: development
          HUSKY: 0
      - name: Build docker image
        run: docker build -t one-app:at-test . --build-arg USER=root --build-arg VERSION=$(cat .nvmrc)
      - name: Run Integration Tests
        run: ONE_DANGEROUSLY_SKIP_ONE_APP_IMAGE_BUILD=true npm run test:integration
      - name: Archive log & trace files
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: logs-and-traces
          path: prod-sample/otel-collector/tmp/*.jsonl
          overwrite: true
          retention-days: 5
