name: "[on PR] DangerJS"
on: pull_request
jobs:
  dangerJS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: npm install
      run: npm ci
      env:
        NODE_ENV: development
        HUSKY: 0
    - name: Danger
      run: npm run test:danger
      env:
        NODE_ENV: production
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
