name: "[on PR] One App Integration Tests"
on: pull_request
jobs:
  one-app-integration-pr:
    name:  One App Integration Tests - PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: npm install
        run: NODE_ENV=development npm ci
      - name: Build docker image
        run: docker build -t one-app:at-test . --build-arg USER=root
      - name: Run Integration Tests
        run: ONE_DANGEROUSLY_SKIP_ONE_APP_IMAGE_BUILD=true npm run test:integration
